Loading the excel data file into pandas using the read_excel() function.
Locating the directory of the excel file at first which is more efficient to keep the dataset in the same directory.

**Data= pd.read_excel(r”File_location”)**

r stands for "raw" and will cause backslashes in the string to be interpreted as actual backslashes rather than special characters.

In [1]:
import pandas as pd
import os

In [2]:
pwd

'/content'

In [4]:
variable = pd.read_csv("/content/Crude Oil Prices Daily.csv")
variable.head()

       Date  Closing Value
0  1/2/1986          25.56
1  1/3/1986          26.00
2  1/6/1986          26.53
3  1/7/1986          25.85
4  1/8/1986          25.87

In [5]:
variable = pd.read_csv(r"/content/Crude Oil Prices Daily.csv")
variable.head()

       Date  Closing Value
0  1/2/1986          25.56
1  1/3/1986          26.00
2  1/6/1986          26.53
3  1/7/1986          25.85
4  1/8/1986          25.87